#!/bin/bash

# Assign LEAN_SYSROOT if unassigned
: "${LEAN_SYSROOT:=$HOME/.elan/toolchains/leanprover--lean4---nightly}"

# Grab the path to the folder containing this file
ROOT="${BASH_SOURCE%/*}"

echo "PWD=$PWD"
echo "ROOT=$ROOT"
echo "LEAN_SYSROOT=$LEAN_SYSROOT"

# If the argument list includes -c, no need for LDFLAGS, but otherwise add LEAN_SYSROOT/lib to the linker path
[[ " $@ " =~ " -c " ]] && LDFLAGS=() || LDFLAGS=(-Wl,-rpath="$LEAN_SYSROOT/lib")

# Run Lean clang (under the name clang++) with requisite llvm headers and the LDFLAGS from above
exec -a clang++ "$LEAN_SYSROOT/bin/clang" "$@" \
  -isystem "$ROOT/lean-llvm/include/x86_64-unknown-linux-gnu/c++/v1" \
  -isystem "$ROOT/lean-llvm/include/c++/v1" \
  -isystem "$LEAN_SYSROOT/include/clang" \
  "${LDFLAGS[@]}"
