name: update std

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:

  check-std:
    name: Check Std repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          STD_HEAD=$(git ls-remote https://github.com/leanprover/std4.git refs/heads/main | awk '{ print $1 }')
          echo "Latest commit to std4/main: $STD_HEAD"

          CUR_VER=$(lake exe wtf std lake-manifest.json)
          echo "Current manifest commmit: $CUR_VER"
