name: update std

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:

  check-std:
    name: Check Std repo
    runs-on: ubuntu-latest

    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2

      - run: |
          STD_HEAD=$(git ls-remote https://github.com/leanprover/std4.git refs/heads/main | awk '{ print $1 }')
          echo "Latest commit to std4/main: $STD_HEAD"

          CUR_VER=$(lake exe wtf std lake-manifest.json)
          echo "Current manifest commmit: $CUR_VER"
